import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import "./assets/css/hero-slider.css";
import GreekUppercaseNormalizer from "@/components/common/GreekUppercaseNormalizer";
import Header from "@/components/header/Header";
import FooterRevealLayout from "@/components/footer/FooterRevealLayout";
import { getSiteUrl } from "@/lib/site-url";
import { getBrands } from "@/lib/wp/brands";
import { getFooterSidebars } from "@/lib/wp/footer";
import { getMenuItems } from "@/lib/wp/menu";
import { getSiteSettings } from "@/lib/wp/site";

const openSans = Open_Sans({
  subsets: ["latin", "greek"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-open-sans",
  display: "swap",
});

export async function generateMetadata(): Promise<Metadata> {
  const siteSettings = await getSiteSettings();
  const siteUrl = getSiteUrl();
  const siteName = siteSettings?.name ?? "Coptex Hellas";
  const siteIcon = siteSettings?.siteIcon;
  const iconUrl = siteIcon?.url32 ?? siteIcon?.url ?? undefined;
  const appleIconUrl = siteIcon?.url192 ?? siteIcon?.url512 ?? siteIcon?.url ?? undefined;

  return {
    metadataBase: siteUrl,
    title: siteName,
    description: "Generated by Karma Web Arch",
    icons: iconUrl
      ? {
          icon: iconUrl,
          shortcut: iconUrl,
          apple: appleIconUrl,
        }
      : undefined,
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [menuItems, footerSidebars, siteSettings, brands] = await Promise.all([
    getMenuItems(),
    getFooterSidebars(),
    getSiteSettings(),
    getBrands(),
  ]);

  return (
    <html lang="en">
      <body className={`${openSans.variable} antialiased min-h-screen`}>
        <GreekUppercaseNormalizer />

        {/* Header stays normal, above everything */}
        <Header
          items={menuItems}
          innerClassName="w-full px-4 sm:px-6 lg:px-8 xl:px-12 2xl:px-16"
          logoText={siteSettings?.name ?? "Coptex Hellas"}
          logoUrl={siteSettings?.logo?.url ?? null}
          logoAlt={siteSettings?.logo?.alt ?? siteSettings?.name ?? "Coptex Hellas"}
          logoWidth={siteSettings?.logo?.width ?? null}
          logoHeight={siteSettings?.logo?.height ?? null}
        />

        {/* Content passes over footer; footer reveals at bottom */}
        <FooterRevealLayout sidebars={footerSidebars} brands={brands}>
          {children}
        </FooterRevealLayout>
      </body>
    </html>
  );
}
